import { createServer, type IncomingMessage, type ServerResponse, type Server } from "node:http";
import { timingSafeEqual } from "node:crypto";
import { dirname } from "node:path";
import type Database from "better-sqlite3";
import { openManagedDb } from "../../db/managed-connection.js";
import { SCHEMA_VERSION } from "../../db/schema.js";
import {
  loadDashboardSnapshot,
  DashboardSnapshotError,
  type DashboardFilters,
} from "../snapshot.js";
import {
  readRunMetaFromDb,
  readRunEventsFromDb,
  listRunArtifactsFromDb,
} from "../../core/run-db-reader.js";
import { ReviewProposalRepository } from "../../db/repositories/review-proposals.js";
import { ReviewConsensusRepository } from "../../db/repositories/review-consensus.js";
import { ReviewerRepository } from "../../db/repositories/reviewers.js";
import { readArtifactBlob } from "../../db/artifact-blobs.js";
import {
  findBlobStore,
  findExternalBlob,
  listBlobStores,
  listExternalBlobs,
} from "../../db/blob-stores.js";
import { listArchives } from "../../db/archive-catalog.js";
import { LocalBlobStore } from "../../storage/local-blob-store.js";
import { listActiveDomainLocks } from "../../workspace/db-domain-lock.js";
import { checkConsistency } from "../../db/consistency.js";
import { dbStats } from "../../db/maintenance.js";
import { renderDashboardHtml } from "../render.js";
import {
  listOperations,
  getOperation,
  listOperationEvents,
} from "../../db/repositories/operations.js";
import {
  listAssetExports,
  type AssetType,
} from "../../db/repositories/asset-exports.js";
import {
  getCurrentProjectProfile,
  listProjectProfileRevisions,
} from "../../db/repositories/project-profile-revisions.js";
import {
  getCurrentPolicyTemplate,
  listPolicyTemplates,
  type PolicyScopeType,
} from "../../db/repositories/policy-templates.js";
import {
  getCurrentKnowledgeRevision,
  listKnowledgeRevisions,
  knowledgeEntriesHasCategory,
} from "../../db/repositories/knowledge-entry-revisions.js";

/**
 * Dashboard read-only HTTP server (Phase 12-1 skeleton).
 *
 * Single-file router; Node built-in http. Routes are matched by exact
 * path or `/api/runs/:runId/timeline`-style placeholders. Phase 12 only
 * accepts GET / HEAD; everything else is 405.
 *
 * Subsequent sub-phases (12-2 .. 12-7) extend the route list. The
 * skeleton intentionally keeps a single `routes` table — no framework,
 * no plugin system.
 */

export interface DashboardServerConfig {
  dbPath: string;
  host: string;
  port: number;
  /** Optional bearer token (Phase 12-7). */
  token?: string;
  /** When true (Phase 12-7), block GET /api/artifacts/:id/body. */
  artifactBodyDisabled?: boolean;
  /** Maximum bytes to inline for an artifact body (Phase 12-4). */
  maxInlineArtifactBytes?: number;
  /** Optional CORS origin (Phase 12-7). */
  corsOrigin?: string;
  /**
   * Internal HTTP listener switch used by the operations server. Dashboard
   * creation sanitizes this to false and always serves read-only routes.
   */
  mutationEnabled?: boolean;
  /**
   * Internal CSRF token used by the operations server POST listener.
   */
  csrfToken?: string;
}

export interface RequestContext {
  config: DashboardServerConfig;
}

export interface RouteParams {
  [key: string]: string;
}

export interface ApiError {
  code: string;
  message: string;
  details?: Record<string, unknown>;
}

export interface RouteHandlerInput {
  req: IncomingMessage;
  res: ServerResponse;
  ctx: RequestContext;
  params: RouteParams;
  /** Parsed URL query. */
  query: URLSearchParams;
}

export type RouteHandler = (input: RouteHandlerInput) => Promise<void> | void;

export interface Route {
  method: "GET" | "POST";
  pattern: string;
  handler: RouteHandler;
}

const ROUTE_PARAM_RE = /:([A-Za-z_][A-Za-z0-9_]*)/g;

/**
 * Phase 12 post-close P2 #3: canonical runId validator. Must match the
 * shape generated by `generateRunId` — `run-` prefix + 1..127 chars from
 * `[A-Za-z0-9._-]`. Reject any other shape with 400 bad_request before
 * the value reaches DB helpers / error message echo.
 */
const RUN_ID_SHAPE = /^run-[A-Za-z0-9][A-Za-z0-9._-]{0,127}$/;
function validRunId(s: string): boolean {
  return RUN_ID_SHAPE.test(s);
}

function compilePattern(
  pattern: string,
): { regex: RegExp; params: string[] } {
  const params: string[] = [];
  const escaped = pattern.replace(/[.+?^${}()|[\]\\]/g, "\\$&");
  const re = escaped.replace(ROUTE_PARAM_RE, (_, name: string) => {
    params.push(name);
    return "([^/]+)";
  });
  return { regex: new RegExp(`^${re}$`), params };
}

/** Match a path against a list of routes. Returns route + params or null. */
export function matchRoute(
  routes: Route[],
  method: string,
  pathname: string,
): { route: Route; params: RouteParams } | null {
  // Match METHOD then path: two routes can share a path with different verbs
  // (e.g. GET vs POST /api/runs/:id/review). A path-only match would let a
  // POST be dispatched to the read-only GET handler — a silent no-op for a
  // mutation. HEAD is served by the GET handler.
  const wanted = method === "HEAD" ? "GET" : method;
  for (const route of routes) {
    if (route.method !== wanted) continue;
    const { regex, params: paramNames } = compilePattern(route.pattern);
    const m = regex.exec(pathname);
    if (m === null) continue;
    const params: RouteParams = {};
    paramNames.forEach((name, i) => {
      params[name] = decodeURIComponent(m[i + 1] ?? "");
    });
    return { route, params };
  }
  return null;
}

export function writeJson(
  res: ServerResponse,
  status: number,
  body: unknown,
): void {
  const json = JSON.stringify(body);
  res.statusCode = status;
  res.setHeader("Content-Type", "application/json; charset=utf-8");
  res.setHeader("X-Content-Type-Options", "nosniff");
  res.setHeader("Content-Length", Buffer.byteLength(json).toString());
  res.end(json);
}

export function writeError(
  res: ServerResponse,
  status: number,
  code: string,
  message: string,
  details?: Record<string, unknown>,
): void {
  const err: ApiError = { code, message, ...(details !== undefined ? { details } : {}) };
  writeJson(res, status, { error: err });
}

/** Default route table for the dashboard server. */
export function defaultRoutes(): Route[] {
  return [
    // Operation audit endpoints are read-only dashboard routes so operators can
    // inspect operations created by the separate operations POST listener.
    {
      method: "GET",
      pattern: "/api/operations",
      handler: ({ ctx, res, query }) => {
        const handle = openManagedDb({ dbPath: ctx.config.dbPath, readonly: true });
        try {
          const tt = query.get("targetType");
          const ti = query.get("targetId");
          const st = query.get("status");
          const limit = Number(query.get("limit") ?? "100");
          const rows = listOperations(handle.db, {
            ...(tt !== null ? { targetType: tt } : {}),
            ...(ti !== null ? { targetId: ti } : {}),
            ...(st !== null
              ? {
                  status: st as
                    | "pending"
                    | "running"
                    | "succeeded"
                    | "failed"
                    | "cancelled",
                }
              : {}),
            limit: Number.isFinite(limit) ? limit : 100,
          });
          writeJson(res, 200, { operations: rows });
        } finally {
          handle.close();
        }
      },
    },
    {
      method: "GET",
      pattern: "/api/operations/:operationId",
      handler: ({ ctx, res, params }) => {
        const handle = openManagedDb({ dbPath: ctx.config.dbPath, readonly: true });
        try {
          const op = getOperation(handle.db, params.operationId!);
          if (op === null) {
            writeError(
              res,
              404,
              "not_found",
              `operation ${params.operationId} not found`,
            );
            return;
          }
          const events = listOperationEvents(handle.db, params.operationId!);
          writeJson(res, 200, { operation: op, events });
        } finally {
          handle.close();
        }
      },
    },
    {
      method: "GET",
      pattern: "/api/assets/exports",
      handler: ({ ctx, res, query }) => {
        const handle = openManagedDb({ dbPath: ctx.config.dbPath, readonly: true });
        try {
          const t = query.get("assetType");
          const filter =
            t !== null
              ? { assetType: t as AssetType }
              : {};
          const rows = listAssetExports(handle.db, filter);
          writeJson(res, 200, { exports: rows });
        } finally {
          handle.close();
        }
      },
    },
    {
      method: "GET",
      pattern: "/api/assets/projects",
      handler: ({ ctx, res }) => {
        const handle = openManagedDb({ dbPath: ctx.config.dbPath, readonly: true });
        try {
          const rows = handle.db
            .prepare(
              `SELECT p.project_id, p.repo_id,
                      p.current_profile_revision_id AS currentRevisionId,
                      r.version, r.created_at AS revisionCreatedAt
                 FROM projects p
                 LEFT JOIN project_profile_revisions r
                   ON r.revision_id = p.current_profile_revision_id
                ORDER BY p.project_id`,
            )
            .all();
          writeJson(res, 200, { projects: rows });
        } finally {
          handle.close();
        }
      },
    },
    {
      method: "GET",
      pattern: "/api/assets/policies",
      handler: ({ ctx, res }) => {
        const handle = openManagedDb({ dbPath: ctx.config.dbPath, readonly: true });
        try {
          const templates = handle.db
            .prepare(
              `SELECT scope_type, scope_id, MAX(version) AS currentVersion,
                      COUNT(*) AS revisionCount
                 FROM policy_templates
                GROUP BY scope_type, scope_id
                ORDER BY scope_type, scope_id`,
            )
            .all();
          const snapshots = handle.db
            .prepare(
              `SELECT snapshot_id, run_id, project_id, repo_id, domain,
                      created_at
                 FROM effective_policy_snapshots
                ORDER BY created_at DESC, snapshot_id DESC
                LIMIT 100`,
            )
            .all();
          writeJson(res, 200, { templates, snapshots });
        } finally {
          handle.close();
        }
      },
    },
    {
      method: "GET",
      pattern: "/api/assets/knowledge",
      handler: ({ ctx, res }) => {
        const handle = openManagedDb({ dbPath: ctx.config.dbPath, readonly: true });
        try {
          const rows = handle.db
            .prepare(
              // codebase-knowledge assets view. Operational knowledge
              // (category='operational', issue #57) is excluded here
              // (fail-closed); its own surfaces land in a follow-up. On a
              // pre-v19 schema all rows are codebase → drop the filter.
              `SELECT e.entry_id, e.project_id, e.repo_id, e.domain, e.kind,
                      e.path, e.current_revision_id AS currentRevisionId,
                      r.version, r.title, r.created_at AS revisionCreatedAt
                 FROM knowledge_entries e
                 LEFT JOIN knowledge_entry_revisions r
                   ON r.revision_id = e.current_revision_id
                ${knowledgeEntriesHasCategory(handle.db) ? "WHERE e.category = 'codebase'" : ""}
                ORDER BY e.kind, e.path, e.entry_id
                LIMIT 500`,
            )
            .all();
          writeJson(res, 200, { entries: rows });
        } finally {
          handle.close();
        }
      },
    },
    {
      method: "GET",
      pattern: "/api/assets/projects/:projectId",
      handler: ({ ctx, res, params }) => {
        const handle = openManagedDb({ dbPath: ctx.config.dbPath, readonly: true });
        try {
          const cur = getCurrentProjectProfile(handle.db, params.projectId!);
          if (cur === null) {
            writeError(
              res,
              404,
              "not_found",
              `no current revision for project ${params.projectId}`,
            );
            return;
          }
          const history = listProjectProfileRevisions(
            handle.db,
            params.projectId!,
          );
          writeJson(res, 200, { current: cur, history });
        } finally {
          handle.close();
        }
      },
    },
    {
      method: "GET",
      pattern: "/api/assets/policies/:scopeType/:scopeId",
      handler: ({ ctx, res, params }) => {
        const t = params.scopeType!;
        if (
          t !== "repo" &&
          t !== "project" &&
          t !== "domain" &&
          t !== "global"
        ) {
          writeError(
            res,
            400,
            "bad_request",
            "scopeType must be repo | project | domain | global",
          );
          return;
        }
        const handle = openManagedDb({ dbPath: ctx.config.dbPath, readonly: true });
        try {
          const cur = getCurrentPolicyTemplate(
            handle.db,
            t as PolicyScopeType,
            params.scopeId!,
          );
          if (cur === null) {
            writeError(
              res,
              404,
              "not_found",
              `no policy template for ${t}:${params.scopeId}`,
            );
            return;
          }
          const history = listPolicyTemplates(
            handle.db,
            t as PolicyScopeType,
            params.scopeId!,
          );
          writeJson(res, 200, { current: cur, history });
        } finally {
          handle.close();
        }
      },
    },
    {
      method: "GET",
      pattern: "/api/assets/knowledge/:entryId",
      handler: ({ ctx, res, params }) => {
        const handle = openManagedDb({ dbPath: ctx.config.dbPath, readonly: true });
        try {
          // codebase-only detail surface. Operational entries (issue #57) are
          // excluded so their body/history cannot be fetched here (mirrors the
          // category filter on the listing route). On a pre-v19 schema there is
          // no category column → every row is codebase.
          const isCodebase = knowledgeEntriesHasCategory(handle.db)
            ? ((
                handle.db
                  .prepare("SELECT category FROM knowledge_entries WHERE entry_id = ?")
                  .get(params.entryId!) as { category: string } | undefined
              )?.category === "codebase")
            : true;
          const cur = isCodebase
            ? getCurrentKnowledgeRevision(handle.db, params.entryId!)
            : null;
          if (cur === null) {
            writeError(
              res,
              404,
              "not_found",
              `no current revision for knowledge entry ${params.entryId}`,
            );
            return;
          }
          const history = listKnowledgeRevisions(handle.db, params.entryId!);
          writeJson(res, 200, { current: cur, history });
        } finally {
          handle.close();
        }
      },
    },
    {
      method: "GET",
      pattern: "/api/storage/blobs",
      handler: ({ ctx, res }) => {
        const handle = openManagedDb({ dbPath: ctx.config.dbPath, readonly: true });
        try {
          const dbBlobs = handle.db
            .prepare(
              `SELECT COUNT(*) AS count,
                      COALESCE(SUM(bytes), 0) AS bytes,
                      COALESCE(SUM(stored_bytes), 0) AS storedBytes
                 FROM artifact_blobs`,
            )
            .get();
          writeJson(res, 200, {
            dbBlobs,
            stores: listBlobStores(handle.db),
            externalBlobs: listExternalBlobs(handle.db),
          });
        } finally {
          handle.close();
        }
      },
    },
    {
      method: "GET",
      pattern: "/api/archives",
      handler: ({ ctx, res }) => {
        const handle = openManagedDb({ dbPath: ctx.config.dbPath, readonly: true });
        try {
          writeJson(res, 200, { archives: listArchives(handle.db) });
        } finally {
          handle.close();
        }
      },
    },
    {
      method: "GET",
      pattern: "/api/doctor/latest",
      handler: ({ ctx, res }) => {
        const handle = openManagedDb({ dbPath: ctx.config.dbPath, readonly: true });
        try {
          const run = handle.db
            .prepare(
              `SELECT doctor_run_id, started_at, completed_at, status,
                      summary_json
                 FROM doctor_runs
                ORDER BY started_at DESC
                LIMIT 1`,
            )
            .get() as { doctor_run_id: string } | undefined;
          if (run === undefined) {
            writeJson(res, 200, { run: null, findings: [] });
            return;
          }
          const findings = handle.db
            .prepare(
              `SELECT finding_id, check_id, severity, status, message,
                      repairable, details_json
                 FROM doctor_findings
                WHERE doctor_run_id = ?
                ORDER BY finding_id`,
            )
            .all(run.doctor_run_id);
          writeJson(res, 200, { run, findings });
        } finally {
          handle.close();
        }
      },
    },
    {
      method: "GET",
      pattern: "/api/health",
      handler: ({ ctx, res }) => {
        let dbSchemaVersion: number | null = null;
        try {
          const handle = openManagedDb({ dbPath: ctx.config.dbPath, readonly: true });
          try {
            const r = handle.db
              .prepare("SELECT MAX(version) AS v FROM schema_migrations")
              .get() as { v: number | null } | undefined;
            dbSchemaVersion = r?.v ?? null;
          } finally {
            handle.close();
          }
        } catch {
          // surface as 'db-unavailable' but keep 200 — operator wants to
          // troubleshoot via health when the DB is missing.
        }
        writeJson(res, 200, {
          status: "ok",
          version: "phase12",
          dbSchemaVersion,
          schemaVersionExpected: SCHEMA_VERSION,
          generatedAt: new Date().toISOString(),
        });
      },
    },
    {
      method: "GET",
      pattern: "/api/runs",
      handler: ({ ctx, res, query }) => {
        // List recent runs via the snapshot's recentRuns slice. This
        // reuses the same projection the static dashboard already shows
        // so the UI shape stays consistent.
        const filters: DashboardFilters = {};
        const proj = query.get("project");
        const repo = query.get("repo");
        if (proj !== null) filters.projectId = proj;
        if (repo !== null) filters.repoId = repo;
        try {
          const snap = loadDashboardSnapshot({
            harnessRoot: dirname(dirname(ctx.config.dbPath)),
            filters,
            autoImport: false,
          });
          writeJson(res, 200, { runs: snap.recentRuns });
        } catch (e) {
          if (e instanceof DashboardSnapshotError) {
            writeError(res, 404, "not_found", e.message);
            return;
          }
          throw e;
        }
      },
    },
    {
      method: "GET",
      pattern: "/api/runs/:runId",
      handler: ({ ctx, res, params }) => {
        const runId = params.runId!;
        if (!validRunId(runId)) {
          writeError(res, 400, "bad_request", "invalid runId shape");
          return;
        }
        const meta = readRunMetaFromDb(ctx.config.dbPath, runId);
        if (meta === null) {
          writeError(res, 404, "not_found", `run ${runId} not found`);
          return;
        }
        writeJson(res, 200, meta);
      },
    },
    {
      method: "GET",
      pattern: "/api/runs/:runId/timeline",
      handler: ({ ctx, res, params }) => {
        const runId = params.runId!;
        if (!validRunId(runId)) {
          writeError(res, 400, "bad_request", "invalid runId shape");
          return;
        }
        const events = readRunEventsFromDb(ctx.config.dbPath, runId);
        if (events === null) {
          writeError(res, 404, "not_found", `run ${runId} not found`);
          return;
        }
        writeJson(res, 200, { events });
      },
    },
    {
      method: "GET",
      pattern: "/api/runs/:runId/artifacts",
      handler: ({ ctx, res, params }) => {
        const runId = params.runId!;
        if (!validRunId(runId)) {
          writeError(res, 400, "bad_request", "invalid runId shape");
          return;
        }
        const list = listRunArtifactsFromDb(ctx.config.dbPath, runId);
        if (list === null) {
          writeError(res, 404, "not_found", `run ${runId} not found`);
          return;
        }
        writeJson(res, 200, { artifacts: list });
      },
    },
    {
      method: "GET",
      pattern: "/api/runs/:runId/review",
      handler: ({ ctx, res, params }) => {
        const runId = params.runId!;
        if (!validRunId(runId)) {
          writeError(res, 400, "bad_request", "invalid runId shape");
          return;
        }
        const handle = openManagedDb({ dbPath: ctx.config.dbPath, readonly: true });
        try {
          const proposals = new ReviewProposalRepository(handle.db).listForRun(
            runId,
          );
          const consensus = new ReviewConsensusRepository(handle.db).findActive(
            runId,
          );
          writeJson(res, 200, { runId, proposals, consensus });
        } finally {
          handle.close();
        }
      },
    },
    {
      method: "GET",
      pattern: "/api/review/proposals",
      handler: ({ ctx, res, query }) => {
        const runId = query.get("runId");
        if (runId === null) {
          writeError(res, 400, "bad_request", "runId query is required");
          return;
        }
        if (!validRunId(runId)) {
          writeError(res, 400, "bad_request", "invalid runId shape");
          return;
        }
        const handle = openManagedDb({ dbPath: ctx.config.dbPath, readonly: true });
        try {
          const proposals = new ReviewProposalRepository(handle.db).listForRun(
            runId,
            { includeArchived: query.get("includeArchived") === "1" },
          );
          writeJson(res, 200, { runId, proposals });
        } finally {
          handle.close();
        }
      },
    },
    {
      method: "GET",
      pattern: "/api/review/consensus",
      handler: ({ ctx, res, query }) => {
        const runId = query.get("runId");
        if (runId === null) {
          writeError(res, 400, "bad_request", "runId query is required");
          return;
        }
        if (!validRunId(runId)) {
          writeError(res, 400, "bad_request", "invalid runId shape");
          return;
        }
        const handle = openManagedDb({ dbPath: ctx.config.dbPath, readonly: true });
        try {
          const active = new ReviewConsensusRepository(handle.db).findActive(
            runId,
          );
          writeJson(res, 200, { runId, consensus: active });
        } finally {
          handle.close();
        }
      },
    },
    // Phase 12 post-close fix (external review P1-1): `artifact_id` is
    // a TEXT id of the form `<runId>:<relativePath>` (see
    // `src/db/run-artifacts.ts`). The previous handler validated it as a
    // positive integer and the SELECT read a non-existent `byte_size`
    // column (the real column is `bytes`). Both endpoints were broken.
    // The path segment is base64url-encoded so a `:` or `/` in the id
    // does not collide with the URL grammar.
    {
      method: "GET",
      pattern: "/api/artifacts/:artifactIdB64",
      handler: ({ ctx, res, params }) => {
        const id = decodeBase64UrlArtifactId(params.artifactIdB64!);
        if (id === null) {
          writeError(
            res,
            400,
            "bad_request",
            "artifactId must be base64url-encoded (e.g. base64url('run-XYZ:summary.md'))",
          );
          return;
        }
        const handle = openManagedDb({ dbPath: ctx.config.dbPath, readonly: true });
        try {
          const row = handle.db
            .prepare(
              `SELECT artifact_id, run_id, relative_path, content_type,
                      bytes, sha256, blob_sha256, storage,
                      secret_suspect, original_bytes, original_sha256,
                      body_status
                 FROM artifacts
                WHERE artifact_id = ?`,
            )
            .get(id) as Record<string, unknown> | undefined;
          if (row === undefined) {
            writeError(res, 404, "not_found", `artifact ${id} not found`);
            return;
          }
          writeJson(res, 200, row);
        } finally {
          handle.close();
        }
      },
    },
    {
      method: "GET",
      pattern: "/api/artifacts/:artifactIdB64/body",
      handler: async ({ ctx, res, params }) => {
        const id = decodeBase64UrlArtifactId(params.artifactIdB64!);
        if (id === null) {
          writeError(
            res,
            400,
            "bad_request",
            "artifactId must be base64url-encoded (e.g. base64url('run-XYZ:summary.md'))",
          );
          return;
        }
        if (ctx.config.artifactBodyDisabled === true) {
          writeError(
            res,
            403,
            "forbidden",
            "artifact body serving is disabled (--no-artifact-body)",
          );
          return;
        }
        const handle = openManagedDb({ dbPath: ctx.config.dbPath, readonly: true });
        try {
          const row = handle.db
            .prepare(
              `SELECT blob_sha256, bytes, content_type, secret_suspect,
                      relative_path, storage
                 FROM artifacts WHERE artifact_id = ?`,
            )
            .get(id) as
            | {
                blob_sha256: string | null;
                bytes: number | null;
                content_type: string | null;
                secret_suspect: number | null;
                relative_path: string;
                storage: string;
              }
            | undefined;
          if (row === undefined || row.blob_sha256 === null) {
            writeError(
              res,
              404,
              "not_found",
              `artifact ${id} has no DB-stored body`,
            );
            return;
          }
          const max =
            ctx.config.maxInlineArtifactBytes ?? 1024 * 1024;
          const tooLarge =
            row.bytes !== null && row.bytes > max;
          let buf: Buffer | null;
          try {
            buf = await readArtifactBody(handle.db, {
              blobSha256: row.blob_sha256,
              storage: row.storage,
            });
          } catch (e) {
            writeError(
              res,
              409,
              "blob_integrity_error",
              (e as Error).message,
            );
            return;
          }
          if (buf === null) {
            writeError(
              res,
              404,
              "not_found",
              `artifact blob ${row.blob_sha256} missing`,
            );
            return;
          }
          res.statusCode = 200;
          res.setHeader(
            "Content-Type",
            row.content_type ?? "application/octet-stream",
          );
          res.setHeader("X-Content-Type-Options", "nosniff");
          if (row.secret_suspect === 1) {
            res.setHeader("X-Harness-Secret-Suspect", "1");
          }
          if (tooLarge) {
            // download-style: encourage client to save rather than render
            const filename = row.relative_path.split("/").pop() ?? "artifact";
            res.setHeader(
              "Content-Disposition",
              `attachment; filename="${filename.replace(/[^A-Za-z0-9._-]/g, "_")}"`,
            );
          }
          res.setHeader("Content-Length", buf.length.toString());
          res.end(buf);
        } finally {
          handle.close();
        }
      },
    },
    {
      method: "GET",
      pattern: "/api/review/reviewers",
      handler: ({ ctx, res }) => {
        const handle = openManagedDb({ dbPath: ctx.config.dbPath, readonly: true });
        try {
          const reviewers = new ReviewerRepository(handle.db).list();
          writeJson(res, 200, { reviewers });
        } finally {
          handle.close();
        }
      },
    },
    {
      method: "GET",
      pattern: "/",
      handler: ({ ctx, res }) => {
        // Phase 12-6: serve the same read-only HTML the static export
        // writes, but with a live snapshot.
        try {
          const snapshot = loadDashboardSnapshot({
            harnessRoot: dirname(dirname(ctx.config.dbPath)),
            autoImport: false,
          });
          const html = renderDashboardHtml(snapshot);
          res.statusCode = 200;
          res.setHeader("Content-Type", "text/html; charset=utf-8");
          res.setHeader("X-Content-Type-Options", "nosniff");
          res.setHeader("Cache-Control", "no-store");
          res.end(html);
        } catch (e) {
          if (e instanceof DashboardSnapshotError) {
            writeError(res, 404, "not_found", e.message);
            return;
          }
          throw e;
        }
      },
    },
    {
      method: "GET",
      pattern: "/api/db/status",
      handler: ({ ctx, res }) => {
        const handle = openManagedDb({ dbPath: ctx.config.dbPath, readonly: true });
        try {
          const ver = handle.db
            .prepare("SELECT MAX(version) AS v FROM schema_migrations")
            .get() as { v: number | null };
          const runs = handle.db
            .prepare("SELECT count(*) AS n FROM runs")
            .get() as { n: number };
          writeJson(res, 200, {
            dbPath: ctx.config.dbPath,
            schemaVersion: ver.v,
            schemaVersionExpected: SCHEMA_VERSION,
            runs: runs.n,
            generatedAt: new Date().toISOString(),
          });
        } finally {
          handle.close();
        }
      },
    },
    {
      method: "GET",
      pattern: "/api/db/stats",
      handler: ({ ctx, res }) => {
        // Phase 12 post-close P1: hold the shared maintenance lock for
        // the lifetime of dbStats so a concurrent `db restore` cannot
        // swap the DB out mid-stats. dbStats() opens its own raw
        // readonly connection internally; while *this* managed handle
        // is alive, the maintenance lock is held shared so
        // db restore (exclusive) waits.
        const handle = openManagedDb({ dbPath: ctx.config.dbPath, readonly: true });
        try {
          const stats = dbStats(ctx.config.dbPath);
          writeJson(res, 200, stats);
        } catch (e) {
          writeError(
            res,
            500,
            "internal_error",
            (e as Error).message ?? "dbStats failed",
          );
        } finally {
          handle.close();
        }
      },
    },
    {
      method: "GET",
      pattern: "/api/db/consistency",
      handler: ({ ctx, res }) => {
        const handle = openManagedDb({ dbPath: ctx.config.dbPath, readonly: true });
        try {
          const report = checkConsistency({
            db: handle.db,
            harnessRoot: dirname(dirname(ctx.config.dbPath)),
          });
          writeJson(res, 200, report);
        } finally {
          handle.close();
        }
      },
    },
    {
      method: "GET",
      pattern: "/api/locks",
      handler: ({ ctx, res }) => {
        const handle = openManagedDb({ dbPath: ctx.config.dbPath, readonly: true });
        try {
          const locks = listActiveDomainLocks(handle.db);
          writeJson(res, 200, { locks });
        } finally {
          handle.close();
        }
      },
    },
    {
      method: "GET",
      pattern: "/api/snapshot",
      handler: ({ ctx, res, query }) => {
        // Phase 12-2: DashboardSnapshot live from the DB. The server
        // never auto-imports (autoImport: false enforces read-only).
        // Phase 12 minimum filters: project / repo are the only fields
        // supported by DashboardFilters at this point. domain / status /
        // since / until query params are accepted but silently ignored
        // (forward-compatible for Phase 14+ wiring).
        const filters: DashboardFilters = {};
        const proj = query.get("project");
        const repo = query.get("repo");
        if (proj !== null) filters.projectId = proj;
        if (repo !== null) filters.repoId = repo;

        try {
          const snapshot = loadDashboardSnapshot({
            harnessRoot: dirname(dirname(ctx.config.dbPath)),
            filters,
            autoImport: false,
          });
          writeJson(res, 200, snapshot);
        } catch (e) {
          if (e instanceof DashboardSnapshotError) {
            writeError(res, 404, "not_found", e.message);
            return;
          }
          throw e;
        }
      },
    },
  ];
}

/**
 * Phase 12-7: Authorization gate.
 *
 *   - token unset + localhost (127.0.0.1 / ::1) → skip (operator UX).
 *   - token unset + non-local → 401 (server should not have started in
 *     that shape without an explicit warning; fail-closed regardless).
 *   - token set → require `Authorization: Bearer <token>` on every
 *     request.
 */
function isLocalHost(host: string): boolean {
  return (
    host === "127.0.0.1" ||
    host === "::1" ||
    host === "localhost" ||
    host === "::ffff:127.0.0.1"
  );
}

/**
 * Phase 12 post-close fix (external review P1-1): decode the base64url
 * URL segment back to the canonical `<runId>:<relativePath>` artifact id.
 * Returns null if the segment is empty / not a string. Loose-form
 * `+`/`/`/`=` are also tolerated so curl users who don't strictly use
 * base64url still work.
 */
function decodeBase64UrlArtifactId(seg: string): string | null {
  if (typeof seg !== "string" || seg.length === 0) return null;
  // accept base64 too — replace url-safe chars and add padding.
  const padded = seg
    .replace(/-/g, "+")
    .replace(/_/g, "/")
    .padEnd(Math.ceil(seg.length / 4) * 4, "=");
  try {
    const decoded = Buffer.from(padded, "base64").toString("utf8");
    // canonical artifact ids contain ':'; reject obvious junk so a
    // mistyped numeric id does not silently match nothing.
    if (decoded.length === 0) return null;
    return decoded;
  } catch {
    return null;
  }
}

async function readArtifactBody(
  db: Database.Database,
  input: { blobSha256: string; storage: string },
): Promise<Buffer | null> {
  if (input.storage === "db") {
    return readArtifactBlob(db, input.blobSha256);
  }
  if (input.storage !== "external") return null;
  const external = findExternalBlob(db, input.blobSha256);
  if (external === null || external.status !== "available") return null;
  const storeRow = findBlobStore(db, external.storeId);
  if (storeRow === null || storeRow.storeType !== "local") return null;
  const config = JSON.parse(storeRow.configJson) as { root?: unknown };
  if (typeof config.root !== "string") return null;
  return new LocalBlobStore({ root: config.root }).get({
    sha256: external.sha256,
    uri: external.uri,
  });
}

/**
 * Constant-time string compare. Returns false (not throws) when lengths
 * differ so callers can use a single boolean check.
 */
function safeStringEqual(a: string, b: string): boolean {
  const ab = Buffer.from(a, "utf8");
  const bb = Buffer.from(b, "utf8");
  if (ab.length !== bb.length) return false;
  return timingSafeEqual(ab, bb);
}

function checkAuth(
  req: IncomingMessage,
  config: DashboardServerConfig,
): { ok: true } | { ok: false; status: number; code: string; message: string } {
  const tokenConfigured = config.token !== undefined && config.token !== "";
  // Operations mutation mode MUST have a bearer token, even on localhost.
  // Without one a local process could POST to /api/runs/:id/review and bypass
  // review governance.
  if (config.mutationEnabled === true && !tokenConfigured) {
    return {
      ok: false,
      status: 401,
      code: "unauthorized",
      message:
        "operations serve requires a bearer token (--token-env). " +
        "Read-only dashboard serve still works without one.",
    };
  }
  // Read-only + local + no token → skip (existing operator UX).
  if (!tokenConfigured) {
    if (isLocalHost(config.host)) return { ok: true };
    return {
      ok: false,
      status: 401,
      code: "unauthorized",
      message:
        "dashboard bound non-local but no bearer token configured (--token-env)",
    };
  }
  const header = req.headers.authorization ?? "";
  const expected = `Bearer ${config.token}`;
  if (!safeStringEqual(header, expected)) {
    return {
      ok: false,
      status: 401,
      code: "unauthorized",
      message: "missing or invalid Authorization: Bearer <token>",
    };
  }
  return { ok: true };
}

function setSecurityHeaders(
  res: ServerResponse,
  config: DashboardServerConfig,
): void {
  res.setHeader("X-Content-Type-Options", "nosniff");
  res.setHeader("X-Frame-Options", "DENY");
  res.setHeader("Referrer-Policy", "no-referrer");
  if (config.corsOrigin !== undefined && config.corsOrigin !== "") {
    res.setHeader("Access-Control-Allow-Origin", config.corsOrigin);
    res.setHeader("Vary", "Origin");
  }
}

/** Build the request listener. Exposed so tests can drive directly. */
export function buildListener(
  routes: Route[],
  config: DashboardServerConfig,
): (req: IncomingMessage, res: ServerResponse) => void {
  return async (req, res) => {
    try {
      setSecurityHeaders(res, config);
      const ctx: RequestContext = { config };
      const url = new URL(
        req.url ?? "/",
        `http://${req.headers.host ?? "localhost"}`,
      );
      const pathname = url.pathname;

      // Phase 12-7 auth gate before method check so /api/health does not
      // leak schema_version on unauthorized requests.
      const auth = checkAuth(req, config);
      if (!auth.ok) {
        writeError(res, auth.status, auth.code, auth.message);
        return;
      }

      // Dashboard defines GET/HEAD read routes. Operations serve enables POST
      // for mutation routes. Every other verb (PUT/PATCH/DELETE/...) is 405,
      // not 404 — keep the contract explicit rather than relying on a later
      // route miss.
      const isPost = req.method === "POST";

      if (
        req.method !== "GET" &&
        req.method !== "HEAD" &&
        !(isPost && config.mutationEnabled === true)
      ) {
        writeError(
          res,
          405,
          "method_not_allowed",
          `${config.mutationEnabled === true ? "operations" : "dashboard"} accepts GET / HEAD${
            config.mutationEnabled === true ? " / POST" : ""
          } only (got ${req.method ?? "?"})`,
        );
        return;
      }

      // CSRF for operations POST. Token check is the bearer auth gate above;
      // CSRF is an additional same-origin defense. csrfToken is required when
      // mutationEnabled, and compared in constant time.
      if (req.method === "POST" && config.mutationEnabled === true) {
        const expected = config.csrfToken;
        if (expected === undefined || expected === "") {
          writeError(
            res,
            500,
            "internal_error",
            "operations serve requires a csrf token (server misconfigured)",
          );
          return;
        }
        const got = req.headers["x-csrf-token"];
        if (typeof got !== "string" || !safeStringEqual(got, expected)) {
          writeError(
            res,
            403,
            "forbidden",
            "missing or invalid X-CSRF-Token header",
          );
          return;
        }
      }

      const match = matchRoute(routes, req.method ?? "GET", pathname);
      if (match === null) {
        writeError(res, 404, "not_found", `no route for ${pathname}`);
        return;
      }
      await match.route.handler({
        req,
        res,
        ctx,
        params: match.params,
        query: url.searchParams,
      });
    } catch (e) {
      try {
        writeError(
          res,
          500,
          "internal_error",
          (e as Error).message ?? "unknown error",
        );
      } catch {
        // res already closed — best-effort
      }
    }
  };
}

export function createDashboardServer(
  config: DashboardServerConfig,
  routes?: Route[],
): Server {
  const effective = routes ?? defaultRoutes();
  const {
    mutationEnabled: _mutationEnabled,
    csrfToken: _csrfToken,
    ...readOnlyConfig
  } = config;
  return createServer(
    buildListener(effective, {
      ...readOnlyConfig,
      mutationEnabled: false,
    }),
  );
}
