// route パターン照合と JSON/error 応答の helper。
import type { Route, RouteParams, ApiError } from "./server-types.js";
import type { ServerResponse } from "node:http";

const ROUTE_PARAM_RE = /:([A-Za-z_][A-Za-z0-9_]*)/g;

/**
 * Phase 12 post-close P2 #3: canonical runId validator. Must match the
 * shape generated by `generateRunId` — `run-` prefix + 1..127 chars from
 * `[A-Za-z0-9._-]`. Reject any other shape with 400 bad_request before
 * the value reaches DB helpers / error message echo.
 */
const RUN_ID_SHAPE = /^run-[A-Za-z0-9][A-Za-z0-9._-]{0,127}$/;
export function validRunId(s: string): boolean {
  return RUN_ID_SHAPE.test(s);
}

function compilePattern(
  pattern: string,
): { regex: RegExp; params: string[] } {
  const params: string[] = [];
  const escaped = pattern.replace(/[.+?^${}()|[\]\\]/g, "\\$&");
  const re = escaped.replace(ROUTE_PARAM_RE, (_, name: string) => {
    params.push(name);
    return "([^/]+)";
  });
  return { regex: new RegExp(`^${re}$`), params };
}

/** Match a path against a list of routes. Returns route + params or null. */
export function matchRoute(
  routes: Route[],
  method: string,
  pathname: string,
): { route: Route; params: RouteParams } | null {
  // Match METHOD then path: two routes can share a path with different verbs
  // (e.g. GET vs POST /api/runs/:id/review). A path-only match would let a
  // POST be dispatched to the read-only GET handler — a silent no-op for a
  // mutation. HEAD is served by the GET handler.
  const wanted = method === "HEAD" ? "GET" : method;
  for (const route of routes) {
    if (route.method !== wanted) continue;
    const { regex, params: paramNames } = compilePattern(route.pattern);
    const m = regex.exec(pathname);
    if (m === null) continue;
    const params: RouteParams = {};
    paramNames.forEach((name, i) => {
      params[name] = decodeURIComponent(m[i + 1] ?? "");
    });
    return { route, params };
  }
  return null;
}

export function writeJson(
  res: ServerResponse,
  status: number,
  body: unknown,
): void {
  const json = JSON.stringify(body);
  res.statusCode = status;
  res.setHeader("Content-Type", "application/json; charset=utf-8");
  res.setHeader("X-Content-Type-Options", "nosniff");
  res.setHeader("Content-Length", Buffer.byteLength(json).toString());
  res.end(json);
}

export function writeError(
  res: ServerResponse,
  status: number,
  code: string,
  message: string,
  details?: Record<string, unknown>,
): void {
  const err: ApiError = { code, message, ...(details !== undefined ? { details } : {}) };
  writeJson(res, status, { error: err });
}
