import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { dirname } from "node:path";
import { stringify as yamlStringify } from "yaml";
import type { GlobalPolicy, RepoPolicy } from "../policy/schema.js";
import { ProjectError } from "../project/errors.js";

/**
 * (#78) Materialize a compiled project policy to the files `goal orchestrate`
 * reads in repoId mode (`policies/repos/<repoId>.yaml` and `policies/global.yaml`),
 * so a hand-written profile no longer needs a one-off compile script.
 *
 * Writes are deterministic and DB-free (no `effective_policy_snapshots` row — use
 * `policy snapshot` for that). The repo policy is gated by `--force`; the global
 * policy is only **scaffolded when missing** (the #78 ENOENT fix) so a shared /
 * hand-kept `global.yaml` is not clobbered unless `--force` is given.
 */
export interface PolicyCompileProvenance {
  projectId: string;
  repoId: string;
  profileSource: string;
  profileRevisionId: number | null;
  generatedAt: string;
}

export interface WriteCompiledPolicyOpts {
  repoPolicy: RepoPolicy;
  globalPolicy: GlobalPolicy;
  /** destination for the repo policy. */
  repoOut: string;
  /** destination for the global policy, or null to leave global unmanaged. */
  globalOut: string | null;
  force: boolean;
  provenance: PolicyCompileProvenance;
}

function provenanceHeader(
  p: PolicyCompileProvenance,
  kind: "repo" | "global",
): string {
  const rev = p.profileRevisionId !== null ? ` (rev ${p.profileRevisionId})` : "";
  return (
    [
      "# Generated by 'harness policy compile' — do not hand-edit.",
      `# kind: ${kind} policy`,
      `# project: ${p.projectId}`,
      `# repo: ${p.repoId}`,
      `# profile: ${p.profileSource}${rev}`,
      `# generated_at: ${p.generatedAt}`,
      `# Re-run after editing the profile: harness policy compile --project ${p.projectId} --force`,
    ].join("\n") + "\n\n"
  );
}

function writeOne(
  outPath: string,
  header: string,
  body: unknown,
  force: boolean,
): void {
  if (existsSync(outPath) && !force) {
    throw new ProjectError(
      `${outPath} already exists; pass --force to overwrite`,
    );
  }
  mkdirSync(dirname(outPath), { recursive: true });
  writeFileSync(outPath, header + yamlStringify(body), "utf8");
}

/** Returns the absolute paths actually written. */
export function writeCompiledPolicyFiles(opts: WriteCompiledPolicyOpts): string[] {
  const written: string[] = [];
  writeOne(
    opts.repoOut,
    provenanceHeader(opts.provenance, "repo"),
    opts.repoPolicy,
    opts.force,
  );
  written.push(opts.repoOut);
  // Global is only (re)written when it is missing — or when --force is given.
  // The missing case is the #78 fix (orchestrate would otherwise ENOENT on
  // `policies/global.yaml`); an existing global is left untouched without --force.
  if (
    opts.globalOut !== null &&
    (!existsSync(opts.globalOut) || opts.force)
  ) {
    writeOne(
      opts.globalOut,
      provenanceHeader(opts.provenance, "global"),
      opts.globalPolicy,
      opts.force,
    );
    written.push(opts.globalOut);
  }
  return written;
}
