import { describe, it, expect } from "vitest";
import { mkdirSync, mkdtempSync, readFileSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { writeCompiledPolicyFiles } from "../../../src/cli/policy-compile.js";
import { loadRepoPolicy, loadGlobalPolicy } from "../../../src/policy/loader.js";
import {
  GlobalPolicySchema,
  RepoPolicySchema,
} from "../../../src/policy/schema.js";

const repoPolicy = RepoPolicySchema.parse({
  repo_id: "demo-repo",
  domains: { "apps/web": { write: ["apps/web/**"] } },
});
const globalPolicy = GlobalPolicySchema.parse({ always_deny_write: ["**/.env"] });

const provenance = {
  projectId: "demo",
  repoId: "demo-repo",
  profileSource: "file",
  profileRevisionId: 3,
  generatedAt: "2026-06-11T00:00:00Z",
};

function freshDir(): string {
  return mkdtempSync(join(tmpdir(), "harness-policy-compile-"));
}

describe("writeCompiledPolicyFiles (#78)", () => {
  it("writes the repo policy with a provenance header that round-trips via loadRepoPolicy", async () => {
    const dir = freshDir();
    const repoOut = join(dir, "policies", "repos", "demo-repo.yaml");
    const written = writeCompiledPolicyFiles({
      repoPolicy,
      globalPolicy,
      repoOut,
      globalOut: null,
      force: false,
      provenance,
    });
    expect(written).toEqual([repoOut]);
    const text = readFileSync(repoOut, "utf8");
    expect(text.startsWith("# Generated by 'harness policy compile'")).toBe(true);
    expect(text).toContain("# project: demo");
    // the YAML comments are ignored by the loader; the policy round-trips
    expect(await loadRepoPolicy(repoOut)).toEqual(repoPolicy);
  });

  it("scaffolds global.yaml when missing (the #78 ENOENT fix) and it round-trips", async () => {
    const dir = freshDir();
    const repoOut = join(dir, "policies", "repos", "demo-repo.yaml");
    const globalOut = join(dir, "policies", "global.yaml");
    const written = writeCompiledPolicyFiles({
      repoPolicy,
      globalPolicy,
      repoOut,
      globalOut,
      force: false,
      provenance,
    });
    expect(written).toEqual([repoOut, globalOut]);
    expect(await loadGlobalPolicy(globalOut)).toEqual(globalPolicy);
  });

  it("does NOT overwrite an existing global without --force (left untouched)", () => {
    const dir = freshDir();
    const repoOut = join(dir, "policies", "repos", "demo-repo.yaml");
    const globalOut = join(dir, "policies", "global.yaml");
    mkdirSync(dirname(globalOut), { recursive: true });
    writeFileSync(globalOut, "always_deny_write: []\n", "utf8");
    const written = writeCompiledPolicyFiles({
      repoPolicy,
      globalPolicy,
      repoOut,
      globalOut,
      force: false,
      provenance,
    });
    // repo written, global skipped (already exists)
    expect(written).toEqual([repoOut]);
    expect(readFileSync(globalOut, "utf8")).toBe("always_deny_write: []\n");
  });

  it("refuses to overwrite an existing repo policy without --force", () => {
    const dir = freshDir();
    const repoOut = join(dir, "policies", "repos", "demo-repo.yaml");
    mkdirSync(dirname(repoOut), { recursive: true });
    writeFileSync(repoOut, "stale\n", "utf8");
    expect(() =>
      writeCompiledPolicyFiles({
        repoPolicy,
        globalPolicy,
        repoOut,
        globalOut: null,
        force: false,
        provenance,
      }),
    ).toThrow(/already exists.*--force/);
  });

  it("overwrites both files with --force", () => {
    const dir = freshDir();
    const repoOut = join(dir, "policies", "repos", "demo-repo.yaml");
    const globalOut = join(dir, "policies", "global.yaml");
    mkdirSync(dirname(repoOut), { recursive: true });
    mkdirSync(dirname(globalOut), { recursive: true });
    writeFileSync(repoOut, "stale-repo\n", "utf8");
    writeFileSync(globalOut, "stale-global\n", "utf8");
    const written = writeCompiledPolicyFiles({
      repoPolicy,
      globalPolicy,
      repoOut,
      globalOut,
      force: true,
      provenance,
    });
    expect(written).toEqual([repoOut, globalOut]);
    expect(readFileSync(repoOut, "utf8")).not.toContain("stale-repo");
    expect(readFileSync(globalOut, "utf8")).not.toContain("stale-global");
  });
});
