import { readFile, writeFile, appendFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import { join } from "node:path";
import type { RunMeta, RunStatus } from "../logging/run-log.js";
import { gitCli } from "../git/git-cli.js";
import { acquireDomainLock } from "../workspace/domain-lock.js";

export interface CleanupOpts {
  runsDir: string;
  workspacesDir: string;
  /**
   * locksDir is required: cleanup mutates git refs that `harness run` for the
   * same domain may want to create, so we acquire the same per-domain lock
   * to avoid a race with a concurrent run.
   */
  locksDir: string;
  runId: string;
  /** allow cleaning failed-* / needs_review / verified / generated runs */
  force?: boolean;
  /** override git invocation timeout */
  gitTimeoutMs?: number;
}

export interface CleanupResult {
  runId: string;
  /** true if a worktree existed and was removed by this call */
  worktreeRemoved: boolean;
  /** true if a branch existed and was removed by this call */
  branchRemoved: boolean;
  /** status BEFORE cleanup (post-cleanup is always "cleaned" or unchanged on no-op) */
  previousStatus: RunStatus;
}

/**
 * Thrown when cleanup is rejected by the status gate (e.g. status=needs_review
 * without --force, or status=changes_requested). The CLI maps this to exit
 * code 1, distinct from unexpected exceptions (exit 2).
 */
export class CleanupGateError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "CleanupGateError";
  }
}

const RUN_STATUS_SET = new Set<RunStatus>([
  "running",
  "generated",
  "verified",
  "needs_review",
  "approved",
  "changes_requested",
  "rejected",
  "cleaned",
  "failed-policy-violation",
  "failed-codex",
  "failed-codex-timeout",
  "failed-diff-collection",
  "failed-command",
  "failed-internal-error",
]);

// runId must match the same shape generated by generateRunId(): no path
// separators, no '..', stays within runsDir / workspacesDir after join().
const RUN_ID_RE = /^run-[A-Za-z0-9][A-Za-z0-9._-]{0,127}$/;

interface CleanupGate {
  ok: boolean;
  reason?: string;
}

function checkCleanupAllowed(
  status: RunStatus,
  force: boolean,
): CleanupGate {
  if (status === "cleaned") return { ok: true }; // idempotent no-op
  if (status === "running") {
    return { ok: false, reason: "run is still active" };
  }
  if (status === "changes_requested") {
    return {
      ok: false,
      reason:
        "changes_requested runs are retry bases; mark them as rejected first if you want to discard the worktree",
    };
  }
  if (status === "approved" || status === "rejected") return { ok: true };
  if (force) return { ok: true };
  return {
    ok: false,
    reason: `status "${status}" cannot be cleaned without --force`,
  };
}

function validateMeta(meta: unknown, runId: string): RunMeta {
  if (!meta || typeof meta !== "object") {
    throw new Error(`meta.json for ${runId} is not an object`);
  }
  const m = meta as Record<string, unknown>;
  if (m.runId !== runId) {
    throw new Error(
      `meta.json runId (${String(m.runId)}) does not match directory (${runId})`,
    );
  }
  if (typeof m.repoPath !== "string" || m.repoPath === "") {
    throw new Error(`meta.json for ${runId} has invalid repoPath`);
  }
  if (typeof m.runBranch !== "string" || m.runBranch === "") {
    throw new Error(`meta.json for ${runId} has invalid runBranch`);
  }
  if (typeof m.domain !== "string" || m.domain === "") {
    throw new Error(`meta.json for ${runId} has invalid domain`);
  }
  if (
    typeof m.status !== "string" ||
    !RUN_STATUS_SET.has(m.status as RunStatus)
  ) {
    throw new Error(
      `meta.json for ${runId} has unknown status: ${String(m.status)}`,
    );
  }
  return meta as RunMeta;
}

export async function cleanupRun(opts: CleanupOpts): Promise<CleanupResult> {
  if (!RUN_ID_RE.test(opts.runId)) {
    throw new Error(`invalid runId: ${JSON.stringify(opts.runId)}`);
  }
  const runDir = join(opts.runsDir, opts.runId);
  const metaPath = join(runDir, "meta.json");

  let rawMeta: unknown;
  try {
    rawMeta = JSON.parse(await readFile(metaPath, "utf8"));
  } catch (e) {
    throw new Error(
      `failed to read meta.json for ${opts.runId}: ${(e as Error).message}`,
    );
  }
  const meta = validateMeta(rawMeta, opts.runId);

  const gate = checkCleanupAllowed(meta.status, opts.force ?? false);
  if (!gate.ok) {
    throw new CleanupGateError(
      `cannot cleanup ${opts.runId}: ${gate.reason}`,
    );
  }

  // Acquire the same per-domain lock as `harness run` so a concurrent run
  // can't try to create a worktree / branch while we're removing one. Using
  // a distinct lock-runId so failed acquire from a real run is unambiguous.
  const lock = await acquireDomainLock({
    locksDir: opts.locksDir,
    domain: meta.domain,
    runId: `cleanup:${opts.runId}`,
  });

  const worktreePath = join(opts.workspacesDir, opts.runId, "repo");
  const gitOpts: { cwd: string; timeoutMs?: number } = { cwd: meta.repoPath };
  if (opts.gitTimeoutMs !== undefined) gitOpts.timeoutMs = opts.gitTimeoutMs;

  let worktreeRemoved = false;
  let branchRemoved = false;

  try {
    if (existsSync(worktreePath)) {
      const wt = await gitCli(
        ["worktree", "remove", "--force", worktreePath],
        gitOpts,
      );
      if (wt.exitCode !== 0) {
        throw new Error(
          `failed to remove worktree at ${worktreePath}: ${wt.stderr.trim()}`,
        );
      }
      worktreeRemoved = true;
    }

    // Branch removal is independent of worktree state — a previous run might
    // have lost its worktree directory but the branch is still in the repo.
    // Look it up explicitly and surface deletion failure.
    const lookup = await gitCli(
      ["branch", "--list", meta.runBranch],
      gitOpts,
    );
    if (lookup.exitCode === 0 && lookup.stdout.trim() !== "") {
      const del = await gitCli(["branch", "-D", meta.runBranch], gitOpts);
      if (del.exitCode !== 0) {
        throw new Error(
          `branch delete failed for ${meta.runBranch}: ${del.stderr.trim()}`,
        );
      }
      branchRemoved = true;
    }

    const previousStatus = meta.status;
    if (meta.status !== "cleaned") {
      const updated: RunMeta = { ...meta, status: "cleaned" };
      await writeFile(
        metaPath,
        `${JSON.stringify(updated, null, 2)}\n`,
        "utf8",
      );
      await appendFile(
        join(runDir, "events.jsonl"),
        `${JSON.stringify({
          type: "cleaned",
          runId: opts.runId,
          previousStatus,
          worktreeRemoved,
          branchRemoved,
        })}\n`,
        "utf8",
      );
    }

    return {
      runId: opts.runId,
      worktreeRemoved,
      branchRemoved,
      previousStatus,
    };
  } finally {
    await lock.release();
  }
}
