import { readFile, writeFile, appendFile, rm } from "node:fs/promises";
import { existsSync } from "node:fs";
import { join } from "node:path";
import type Database from "better-sqlite3";
import {
  RUN_STATUSES,
  type RunMeta,
  type RunStatus,
} from "../logging/run-log.js";
import { gitCli } from "../git/git-cli.js";
import { acquireDomainLock } from "../workspace/domain-lock.js";
import { openDb } from "../db/connection.js";
import { runMigrations } from "../db/migrations.js";
import { RunRepository } from "../db/repositories/runs.js";
import { assertNoLegacyRuntimeRows } from "../db/legacy-check.js";
import { exportRun, warnIfExportFailed } from "../db/export-files.js";
import { SourceModeError } from "../db/errors.js";

/**
 * How much of a run's footprint to remove.
 * - workspace: worktree + branch + the (now-empty) workspaces/<runId>/ dir.
 *   The run dir is KEPT and meta.status flips to "cleaned" (audit trail).
 * - run: workspace scope + delete runs/<runId>/ entirely. No meta update
 *   is possible afterward (the file is gone); the deletion is the record.
 * - all: run scope + `git worktree prune` to clear any stale worktree
 *   bookkeeping the target repo may still hold.
 */
export type CleanupScope = "workspace" | "run" | "all";

export interface CleanupOpts {
  runsDir: string;
  workspacesDir: string;
  /**
   * locksDir is required: cleanup mutates git refs that `harness run` for the
   * same domain may want to create, so we acquire the same per-domain lock
   * to avoid a race with a concurrent run.
   */
  locksDir: string;
  /** harness DB path — a `db-first` run is cleaned through the DB. */
  dbPath: string;
  runId: string;
  /** allow cleaning failed-* / needs_review / verified / generated runs */
  force?: boolean;
  /** how much to remove; default "workspace" */
  scope?: CleanupScope;
  /** override git invocation timeout */
  gitTimeoutMs?: number;
}

export interface CleanupResult {
  runId: string;
  scope: CleanupScope;
  /** true if a worktree existed and was removed by this call */
  worktreeRemoved: boolean;
  /** true if a branch existed and was removed by this call */
  branchRemoved: boolean;
  /** true if runs/<runId>/ was deleted (scope run / all) */
  runDirRemoved: boolean;
  /** status BEFORE cleanup */
  previousStatus: RunStatus;
}

/**
 * Thrown when cleanup is rejected by the status gate (e.g. status=needs_review
 * without --force, or status=changes_requested). The CLI maps this to exit
 * code 1, distinct from unexpected exceptions (exit 2).
 */
export class CleanupGateError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "CleanupGateError";
  }
}

const RUN_STATUS_SET: ReadonlySet<string> = new Set(RUN_STATUSES);

// runId must match the same shape generated by generateRunId(): no path
// separators, no '..', stays within runsDir / workspacesDir after join().
const RUN_ID_RE = /^run-[A-Za-z0-9][A-Za-z0-9._-]{0,127}$/;

interface CleanupGate {
  ok: boolean;
  reason?: string;
}

function checkCleanupAllowed(
  status: RunStatus,
  force: boolean,
): CleanupGate {
  if (status === "cleaned") return { ok: true }; // idempotent no-op
  if (status === "running") {
    return { ok: false, reason: "run is still active" };
  }
  if (status === "changes_requested") {
    return {
      ok: false,
      reason:
        "changes_requested runs are retry bases; mark them as rejected first if you want to discard the worktree",
    };
  }
  if (status === "approved" || status === "rejected") return { ok: true };
  if (force) return { ok: true };
  return {
    ok: false,
    reason: `status "${status}" cannot be cleaned without --force`,
  };
}

function validateMeta(meta: unknown, runId: string): RunMeta {
  if (!meta || typeof meta !== "object") {
    throw new Error(`meta.json for ${runId} is not an object`);
  }
  const m = meta as Record<string, unknown>;
  if (m.runId !== runId) {
    throw new Error(
      `meta.json runId (${String(m.runId)}) does not match directory (${runId})`,
    );
  }
  if (typeof m.repoPath !== "string" || m.repoPath === "") {
    throw new Error(`meta.json for ${runId} has invalid repoPath`);
  }
  if (typeof m.runBranch !== "string" || m.runBranch === "") {
    throw new Error(`meta.json for ${runId} has invalid runBranch`);
  }
  if (typeof m.domain !== "string" || m.domain === "") {
    throw new Error(`meta.json for ${runId} has invalid domain`);
  }
  if (
    typeof m.status !== "string" ||
    !RUN_STATUS_SET.has(m.status as RunStatus)
  ) {
    throw new Error(
      `meta.json for ${runId} has unknown status: ${String(m.status)}`,
    );
  }
  return meta as RunMeta;
}

async function readMetaFile(
  metaPath: string,
  runId: string,
): Promise<RunMeta> {
  let rawMeta: unknown;
  try {
    rawMeta = JSON.parse(await readFile(metaPath, "utf8"));
  } catch (e) {
    throw new Error(
      `failed to read meta.json for ${runId}: ${(e as Error).message}`,
    );
  }
  return validateMeta(rawMeta, runId);
}

export async function cleanupRun(opts: CleanupOpts): Promise<CleanupResult> {
  if (!RUN_ID_RE.test(opts.runId)) {
    throw new Error(`invalid runId: ${JSON.stringify(opts.runId)}`);
  }
  const scope: CleanupScope = opts.scope ?? "workspace";
  if (scope !== "workspace" && scope !== "run" && scope !== "all") {
    // Core-level guard: callers other than the CLI must not slip an
    // unknown scope into the destructive run/all branch.
    throw new Error(`invalid cleanup scope: ${JSON.stringify(scope)}`);
  }
  const runDir = join(opts.runsDir, opts.runId);
  const metaPath = join(runDir, "meta.json");

  // Open the DB before the lock so an open failure cannot leak a held
  // lock. The DB tells us whether the run is db-first — which decides the
  // canonical source for the lock key and the cleanup gate.
  const db = openDb(opts.dbPath);
  let lock: Awaited<ReturnType<typeof acquireDomainLock>> | undefined;
  try {
    runMigrations(db);
    // Phase 9-11: legacy-file rows must be migrated before runtime writes.
    assertNoLegacyRuntimeRows(db);
    const dbRow = db
      .prepare(
        "SELECT source_mode, domain, repo_id FROM runs WHERE run_id = ?",
      )
      .get(opts.runId) as
      | { source_mode: string; domain: string; repo_id: string | null }
      | undefined;
    if (
      dbRow !== undefined &&
      dbRow.source_mode !== "db-first" &&
      dbRow.source_mode !== "legacy-file"
    ) {
      throw new SourceModeError(
        opts.runId,
        dbRow.source_mode,
        "db-first | legacy-file",
      );
    }
    const dbFirst = dbRow?.source_mode === "db-first";

    // lock key: a db-first run is DB-canonical; a legacy run probes
    // meta.json. The authoritative gate check happens under the lock.
    let lockDomain: string;
    let lockRepoId: string | undefined;
    if (dbFirst && dbRow !== undefined) {
      lockDomain = dbRow.domain;
      lockRepoId = dbRow.repo_id ?? undefined;
    } else {
      const probe = await readMetaFile(metaPath, opts.runId);
      lockDomain = probe.domain;
      lockRepoId =
        typeof probe.repoId === "string" ? probe.repoId : undefined;
    }
    lock = await acquireDomainLock({
      locksDir: opts.locksDir,
      domain: lockDomain,
      runId: `cleanup:${opts.runId}`,
      ...(lockRepoId !== undefined ? { repoId: lockRepoId } : {}),
    });
    return await cleanupUnderLock(opts, scope, runDir, metaPath, db, dbFirst);
  } finally {
    try {
      db.close();
    } finally {
      if (lock !== undefined) await lock.release();
    }
  }
}

async function cleanupUnderLock(
  opts: CleanupOpts,
  scope: CleanupScope,
  runDir: string,
  metaPath: string,
  db: Database.Database,
  dbFirst: boolean,
): Promise<CleanupResult> {
  // The git operations need repoPath / runBranch and the gate needs the
  // status. For a db-first run these come from the canonical DB row — the
  // exported run dir may not even exist on a re-cleanup. A legacy run
  // reads meta.json.
  let repoPath: string;
  let runBranch: string;
  let currentStatus: RunStatus;
  let legacyMeta: RunMeta | null = null;
  if (dbFirst) {
    const row = db
      .prepare(
        "SELECT repo_path, run_branch, status FROM runs WHERE run_id = ?",
      )
      .get(opts.runId) as
      | {
          repo_path: string | null;
          run_branch: string | null;
          status: string;
        }
      | undefined;
    if (row === undefined) {
      throw new Error(`run ${opts.runId} not found in the DB`);
    }
    if (row.repo_path === null || row.run_branch === null) {
      throw new Error(
        `run ${opts.runId} DB row is missing repo_path / run_branch`,
      );
    }
    repoPath = row.repo_path;
    runBranch = row.run_branch;
    currentStatus = row.status as RunStatus;
  } else {
    legacyMeta = await readMetaFile(metaPath, opts.runId);
    repoPath = legacyMeta.repoPath;
    runBranch = legacyMeta.runBranch;
    currentStatus = legacyMeta.status;
  }

  const gate = checkCleanupAllowed(currentStatus, opts.force ?? false);
  if (!gate.ok) {
    throw new CleanupGateError(
      `cannot cleanup ${opts.runId}: ${gate.reason}`,
    );
  }

  const workspaceRunDir = join(opts.workspacesDir, opts.runId);
  const worktreePath = join(workspaceRunDir, "repo");
  const gitOpts: { cwd: string; timeoutMs?: number } = { cwd: repoPath };
  if (opts.gitTimeoutMs !== undefined) gitOpts.timeoutMs = opts.gitTimeoutMs;

  let worktreeRemoved = false;
  let branchRemoved = false;
  let runDirRemoved = false;

  if (existsSync(worktreePath)) {
    const wt = await gitCli(
      ["worktree", "remove", "--force", worktreePath],
      gitOpts,
    );
    if (wt.exitCode !== 0) {
      throw new Error(
        `failed to remove worktree at ${worktreePath}: ${wt.stderr.trim()}`,
      );
    }
    worktreeRemoved = true;
  }

  // Branch removal is independent of worktree state — a previous run might
  // have lost its worktree directory but the branch is still in the repo.
  // Look it up explicitly and surface deletion failure.
  const lookup = await gitCli(["branch", "--list", runBranch], gitOpts);
  if (lookup.exitCode === 0 && lookup.stdout.trim() !== "") {
    const del = await gitCli(["branch", "-D", runBranch], gitOpts);
    if (del.exitCode !== 0) {
      throw new Error(
        `branch delete failed for ${runBranch}: ${del.stderr.trim()}`,
      );
    }
    branchRemoved = true;
  }

  const previousStatus = currentStatus;

  if (scope === "workspace") {
    // Keep the run dir as audit trail; flip status to cleaned.
    if (dbFirst) {
      // DB-first: the DB row is canonical and is NOT deleted — cleanup
      // flips its status (guarded), records cleanup_actions, re-exports.
      new RunRepository(db).recordCleanup({
        runId: opts.runId,
        scope,
        expectedStatus: currentStatus,
        worktreeRemoved,
        branchRemoved,
      });
      warnIfExportFailed(exportRun(db, opts.runId, { runsDir: opts.runsDir }));
    } else if ((legacyMeta as RunMeta).status !== "cleaned") {
      const updated: RunMeta = { ...(legacyMeta as RunMeta), status: "cleaned" };
      await writeFile(
        metaPath,
        `${JSON.stringify(updated, null, 2)}\n`,
        "utf8",
      );
      await appendFile(
        join(runDir, "events.jsonl"),
        `${JSON.stringify({
          type: "cleaned",
          runId: opts.runId,
          scope,
          previousStatus,
          worktreeRemoved,
          branchRemoved,
        })}\n`,
        "utf8",
      );
    }
  } else {
    // run / all: delete runs/<runId>/. For a db-first run the canonical
    // state is the DB row (kept) — only the exported files are removed.
    // The DB write happens first, the `run_dir_remove` action is recorded
    // only AFTER the rm succeeds so the audit log never claims a deletion
    // that did not happen.
    if (dbFirst) {
      const repo = new RunRepository(db);
      repo.recordCleanup({
        runId: opts.runId,
        scope,
        expectedStatus: currentStatus,
        worktreeRemoved,
        branchRemoved,
      });
      await rm(runDir, { recursive: true, force: true });
      runDirRemoved = true;
      repo.recordCleanupAction(opts.runId, "run_dir_remove", "done");
    } else {
      await rm(runDir, { recursive: true, force: true });
      runDirRemoved = true;
    }
  }

  // Remove the (now-empty) workspaces/<runId>/ parent dir for every scope.
  await rm(workspaceRunDir, { recursive: true, force: true });

  if (scope === "all") {
    // Clear any stale worktree bookkeeping the target repo still holds.
    // This is repo-wide (not just this run) — appropriate for "all".
    const prune = await gitCli(["worktree", "prune"], gitOpts);
    if (prune.exitCode !== 0 || prune.timedOut) {
      throw new Error(
        `git worktree prune failed (exit ${prune.exitCode}${prune.timedOut ? ", timed out" : ""}): ${prune.stderr.trim()}`,
      );
    }
  }

  return {
    runId: opts.runId,
    scope,
    worktreeRemoved,
    branchRemoved,
    runDirRemoved,
    previousStatus,
  };
}
