import { readFile } from "node:fs/promises";
import { join } from "node:path";
import type { RunMeta } from "../logging/run-log.js";
import { loadReviewDecision } from "./review-decision-loader.js";

/**
 * Thrown when a rerun is refused for a user-fixable reason (parent missing,
 * parent in wrong status, malformed review-decision). CLI maps to exit 1.
 */
export class RerunGateError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "RerunGateError";
  }
}

const RUN_ID_RE = /^run-[A-Za-z0-9][A-Za-z0-9._-]{0,127}$/;

export interface RerunPrepResult {
  parentRunId: string;
  repoId: string;
  domain: string;
  baseBranch: string;
  /** the prompt for the next codex run: original goal + required_changes block */
  goal: string;
}

/**
 * Read a parent run's meta + review-decision and prepare the inputs for a
 * follow-up `harness run`. Does NOT itself invoke the workflow — that
 * happens in CLI so it stays composable with the existing entry point.
 */
export async function prepareRerunFromReview(opts: {
  runsDir: string;
  parentRunId: string;
}): Promise<RerunPrepResult> {
  if (!RUN_ID_RE.test(opts.parentRunId)) {
    throw new RerunGateError(
      `invalid parentRunId: ${JSON.stringify(opts.parentRunId)}`,
    );
  }
  const runDir = join(opts.runsDir, opts.parentRunId);
  const metaPath = join(runDir, "meta.json");
  const decisionPath = join(runDir, "review-decision.yaml");

  let metaRaw: unknown;
  try {
    metaRaw = JSON.parse(await readFile(metaPath, "utf8"));
  } catch (e) {
    throw new RerunGateError(
      `failed to read meta.json for ${opts.parentRunId}: ${(e as Error).message}`,
    );
  }
  if (!metaRaw || typeof metaRaw !== "object" || Array.isArray(metaRaw)) {
    throw new RerunGateError(
      `meta.json for ${opts.parentRunId} is not an object`,
    );
  }
  const meta = metaRaw as RunMeta;

  if (meta.status !== "changes_requested") {
    throw new RerunGateError(
      `parent run ${opts.parentRunId} status is "${meta.status}", only changes_requested can be reused as a rerun base`,
    );
  }
  if (
    typeof meta.repoId !== "string" ||
    typeof meta.domain !== "string" ||
    typeof meta.baseBranch !== "string"
  ) {
    throw new RerunGateError(
      `meta.json for ${opts.parentRunId} is missing repoId / domain / baseBranch`,
    );
  }

  let decision: Awaited<ReturnType<typeof loadReviewDecision>>;
  try {
    decision = await loadReviewDecision(decisionPath);
  } catch (e) {
    throw new RerunGateError(
      `failed to read review-decision.yaml for ${opts.parentRunId}: ${(e as Error).message}`,
    );
  }

  // We don't strictly require required_changes (a rerun can be re-attempted
  // with the same goal). But surface a warning-style gate when both
  // decision and required_changes are empty — likely operator confusion.
  if (
    decision.decision !== "changes_requested" ||
    decision.required_changes.length === 0
  ) {
    throw new RerunGateError(
      `${opts.parentRunId} review-decision.yaml must have decision=changes_requested and at least one required_changes entry`,
    );
  }

  // Recover the original goal from the parent's codex-prompt.md. The codex
  // prompt format is generated by buildCodexPrompt(); the line right after
  // "Goal:" is the operator's task description. If we can't recover it we
  // fall back to a stub so the new prompt still has shape.
  let parentGoal = "(parent goal could not be recovered)";
  try {
    const prompt = await readFile(join(runDir, "codex-prompt.md"), "utf8");
    const m = prompt.match(/^Goal:\s*\n([\s\S]*?)\n\nTarget domain:/m);
    if (m && m[1]) parentGoal = m[1].trim();
  } catch {
    // best effort; we already have a fallback
  }

  const changesBullets = decision.required_changes
    .map((c) => `- ${c}`)
    .join("\n");
  const goal = [
    parentGoal,
    "",
    "## Required changes from the previous review",
    "",
    `Previous run: ${opts.parentRunId} (status: changes_requested)`,
    `Reviewer: ${decision.reviewer ?? "(unknown)"}`,
    "",
    "Apply these specific changes on top of the previous attempt:",
    changesBullets,
  ].join("\n");

  return {
    parentRunId: opts.parentRunId,
    repoId: meta.repoId,
    domain: meta.domain,
    baseBranch: meta.baseBranch,
    goal,
  };
}
